apiVersion: v1
kind: Namespace
metadata:
  name: sep6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sep6
  namespace: sep6
  labels:
    app: sep6
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sep6
  template:
    metadata:
      labels:
        app: sep6
    spec:
      containers:
        - name: sep6
          image: sep6:v1
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
         - name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: sep6
  namespace: sep6
  labels:
    app: sep6
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: sep6
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sep6
  namespace: sep6
  labels:
    app: sep6
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: sep6.af678ec0629b4712bb16.germanywestcentral.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: sep6
            port: 
              number: 80