//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP6Film
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class movie
    {
        //public movie(int movie_id, int user_id)
        //{
        //    this.movie_id = movie_id;
        //    this.user_id = user_id;
        //}

        //public movie()
        //{
        //}

        [Key]
        [Column(Order = 1)]
        public int movie_id { get; set; }
        [Key]
        [Column(Order = 2)]
        public int user_id { get; set; }

    }
}
